spring:
  application:
    name: QRMenu
  datasource:
    url: jdbc:mysql://localhost:3306/qrmenu_dev?createDatabaseIfNotExist=true
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  jwt:
    secret: ${JWT_SECRET}
twilio:
  sid: ${TWILIO_ACCOUNT_SID}
  token: ${TWILIO_AUTH_TOKEN}